name: blossombud
favicon: null
layout_spectrum: 0.72107108309865
typography_spectrum: 0.2025369198527187
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.030048491433262825
  lightness: 0.060651281382888556
  saturation: 0.05438186717219651
  rhythmicContrast: 0.4662955109961331
purpose: []
